name: daily-cron
on:
  schedule:
    - cron: '30 7 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --url '${{ secrets.DEPLOY_URL }}'